server:
  port: 9999
spring:
  application:
    name: test_common_modul
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.50.130:3306/docker_demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://127.0.0.1:3306/docker_demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
#    password: root
    password: lk0313
    druid:
      #初始化连接池大小
      initialSize: 10
      #最大空闲值.当经过一个高峰时间后，连接池可以慢慢将已经用不到的连接慢慢释放一部分，一直减少到maxIdle为止
      minIdle: 1
      #最大活跃数
      maxActive: 50
      #最大建立连接等待时间。如果超过此时间将接到异常。设为－1表示无限制
      maxWait: 60000
      #失效检查线程运行时间间隔，要小于MySQL默认
      timeBetweenEvictionRunsMillis: 60000
      #连接的超时时间，默认为半小时
      minEvictableIdleTimeMillis: 300000
      #开启池的prepared statement 池功能
      poolPreparedStatements: false
      #statement池能够同时分配的打开的statements的最大数量
      maxOpenPreparedStatements: 50
  redis:
    host: 192.168.50.130
    port: 6379
    lettuce:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 1000
mybatis-plus:
  mapper-locations: classpath*:mrkay/show/mapper/*.xml